#!/usr/bin/env python3
"""Fetch Web of Science metrics for the lab's ResearcherID and write data/wos-metrics.js.

Uses the Clarivate Web of Science Starter API (free key at https://developer.clarivate.com).
Run locally:   WOS_API_KEY=... python3 scripts/fetch_wos_metrics.py
Or let the GitHub Action in .github/workflows/update-metrics.yml run it weekly.
"""
import datetime
import json
import os
import pathlib
import sys
import time
import urllib.parse
import urllib.request

RESEARCHER_ID = os.environ.get("WOS_RESEARCHER_ID", "JWP-0390-2024")
API = "https://api.clarivate.com/apis/wos-starter/v1/documents"
OUT = pathlib.Path(__file__).resolve().parent.parent / "data" / "wos-metrics.js"


def fetch_page(key, page):
    params = urllib.parse.urlencode(
        {"q": f"AI=({RESEARCHER_ID})", "db": "WOS", "limit": 50, "page": page}
    )
    req = urllib.request.Request(f"{API}?{params}", headers={"X-ApiKey": key})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def main():
    key = os.environ.get("WOS_API_KEY")
    if not key:
        sys.exit("WOS_API_KEY is not set")

    hits, page = [], 1
    while True:
        data = fetch_page(key, page)
        hits += data.get("hits", [])
        total = data.get("metadata", {}).get("total", 0)
        if len(hits) >= total or not data.get("hits"):
            break
        page += 1
        time.sleep(0.3)  # stay under the Starter API rate limit

    cites = sorted(
        (
            next((c.get("count", 0) for c in h.get("citations", []) if c.get("db") == "WOS"), 0)
            for h in hits
        ),
        reverse=True,
    )
    h_index = sum(1 for i, c in enumerate(cites, 1) if c >= i)
    metrics = {
        "works": len(hits),
        "citations": sum(cites),
        "hIndex": h_index,
        "updated": datetime.date.today().isoformat(),
    }
    OUT.write_text(
        "// Generated by scripts/fetch_wos_metrics.py — do not edit by hand.\n"
        f"window.WOS_METRICS = {json.dumps(metrics, indent=2)};\n"
    )
    print(f"Wrote {OUT}: {metrics}")


if __name__ == "__main__":
    main()
